### ISSUE TITLE
Engine Ignition Sensor Not Working

### ISSUE THREAD

**Issue by tango2590** [G-Two/homeassistant-subaru#28]
Ignition status of the engine consistently shows off. I have a Gen2 vehicle with everything else working. Looking back at the sensor data, it has never actually shown to be "on". I get the confirmation that the engine started on my phone from the MySubaru app, but I was hoping to initiate a voice command through Alexa based on ignition status for an audio confirmation.

**Comment by G-Two** [comment]
@tango2590 the state of the ignition (or any other sensor) is a snapshot in time during the last update from the vehicle. With a remote engine start scenario, the state (assuming no manual location requests have occurred) will be what was reported at the last engine shutdown (i.e. off). The confirmation from the MySubaru app is a based on a success message rather than an updated state. The integration supports the same success notification, but you have to enable it in the integration configuration. This does not update the ignition state, since the success notification message carries no vehicle notification information. As of v0.4.0rc4, I've added an additional vehicle fetch request immediately after a successful remote start/stop, which will hopefully update the state.

**Comment by ACiDGRiM** [comment]
Good to know the remote start/stop include a poll, my flows re-poll the vehicle every 2 minutes after remote start. I will update accordingly

**Comment by G-Two** [comment]
Closed as unable to fix (due to API limitations)
