### ISSUE TITLE
API Error SXM40101& Unavailable Entities

### ISSUE THREAD

**Issue by jarrodsfarrell** [G-Two/homeassistant-subaru#31]
I've been noticing these errors in the logs and whenever the entities for my vehicle become unavailable.

I figure it's a rate-limiting issue, but could be something else. The SXM is confusing since I don't have a subscription to Sirius but do have a subscription for remote services. Could be a coincidence though.

Subaru Crosstrek 2018

**Comment by jarrodsfarrell** [comment]
Using the app works, however.

**Comment by stboch** [comment]
Starlink services are provided by Sirius XM connected vehicle services that's why you see the SXM error. sadly there are a few "just because" type errors that we see. try to provide some logs that might give us some more indication of whats one this is...

**Comment by G-Two** [comment]
Yeah it could be a rate-limiting issue, or an expired backend token that we see on newer vehicles. Since it sounds like it is working sometimes and then not, it could be that your session just needs to be reauthenticated. If you can get me more details I can have the underlying subarulink package detect this and reauth your session when it occurs.

For reference these are the only SXM codes that I have definitions for:
```
# G1 Error Codes
ERROR_G1_NO_SUBSCRIPTION = "SXM40004"
ERROR_G1_STOLEN_VEHICLE = "SXM40005"
ERROR_G1_INVALID_PIN = "SXM40006"
ERROR_G1_SERVICE_ALREADY_STARTED = "SXM40009"
ERROR_G1_PIN_LOCKED = "SXM40017"
```

**Comment by G-Two** [comment]
Closed as stale
